# Generated by Django 5.0.2 on 2024-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('UAN', 'Hryvnia')], default='UAN', max_length=3),
        ),
    ]
